name: Generate Pacman Contribution Graph

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Pacman contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Ravneet-project

      - name: Publish Pacman graph to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
